### ISSUE TITLE
Adding a rounding ability?

### ISSUE THREAD

**Issue by aegis72** [evanspearman/ComfyMath#1]
Any chance you might be able to add rounding? Could really use it. :).

**Comment by evanspearman** [comment]
The FloatUnaryOperator node already has a round operation.

**Comment by aegis72** [comment]
ah, let me look at that. thanks!

**Comment by aegis72** [comment]
That did it! 
![image](https://github.com/evanspearman/ComfyMath/assets/118572301/203d47b4-26c1-47b9-b9a6-31fdae613e92)
