### ISSUE TITLE
It could be much more ratios and resolutions for SDXL

### ISSUE THREAD

**Issue by marhensa** [evanspearman/ComfyMath#2]
maybe it's important for this project.

previously [my custom node](https://github.com/marhensa/sdxl-recommended-res-calc) also have only SDXL resolutions that stated in ComfyUI SDXL examples, but it turns out it much more than just that.

This is the full list of accepted aspect ratios and pixel size is derived from this SDXL paper :
https://arxiv.org/abs/2307.01952 https://arxiv.org/pdf/2307.01952.pdf
Page 17 "We use the following image resolutions for mixed-aspect ratio finetuning as described in Section 2.3"

![260265562-a5eb675f-8261-4d21-a4d5-03312053ab02](https://github.com/evanspearman/ComfyMath/assets/816600/f03e9167-12bb-43ad-98de-d44a9beb522b)

Here's what I add
https://github.com/marhensa/sdxl-recommended-res-calc/issues/2

Maybe you could implement it in your https://github.com/evanspearman/ComfyMath/blob/main/src/comfymath/graphics.py

**Comment by Sheng-Charles** [comment]
Thank you, this helps me a lot

**Comment by evanspearman** [comment]
I've added extended versions of these nodes that incorporate the resolutions in the paper. The original nodes have been left unchanged.
