### ISSUE TITLE
Cannot import name 'TypeAlias'  - Python 3.10 Dependency - Ubuntu 20.04 not supported

### ISSUE THREAD

**Issue by philmaas** [evanspearman/ComfyMath#3]
Apparently Python 3.10 or greater is required.

`0.0 seconds (IMPORT FAILED): /home/ubuntu/dev/comfyui/custom_nodes/ComfyMath`

`Cannot import /home/ubuntu/dev/comfyui/custom_nodes/ComfyMath module for custom nodes: cannot import name 'TypeAlias' from 'typing' (/usr/lib/python3.8/typing.py)`

As per the python docs.
https://docs.python.org/3.10/library/typing.html#typing.TypeAlias

Just leaving this as note for others.

**Comment by alexbofa** [comment]
the same problem. I use paperspace, and this platform has only 3.10

**Comment by evanspearman** [comment]
Fixed
